add support for gyro pools
beethovenxfi/beets-frontend pull request #293
Opened 2023-05-17 06:56 UTC by groninge01

2023-06-02 05:53 UTC, danielmkm commented
Why is this failing to build?

2023-06-02 06:06 UTC, danielmkm requested changes

2023-06-02 06:06 UTC, danielmkm commented on lib/services/pool/pool-gyro.service.ts
> +        const bptZeroPriceImpact = poolWeightedBptForTokensZeroPriceImpact(tokenAmountsIn, this.pool);
price impact is always zero, this isn't needed

2023-06-02 06:06 UTC, danielmkm commented on lib/services/pool/lib/util.ts
> +    pool: GqlPoolWeighted | GqlPoolGyro,
this isn't needed, price impact is always 0 for gryo pools

2023-06-02 06:06 UTC, danielmkm commented on modules/pool/invest/components/PoolInvestTypeChoice.tsx
> +    const { pool, poolService, isGyroPool } = usePool();
bad pattern sir, plz no. Make this a generic concept

2023-06-02 06:36 UTC, groninge01 commented
> Why is this failing to build?

Because it needs changes from the canary backend which aren't yet in production.

2023-06-02 06:40 UTC, groninge01 commented on components/inputs/BeetsTokenInputWithSlider.tsx
> +                            {hasBalance && selectedTokenOption.address !== networkConfig.eth.address.toLowerCase() ? (
It is. Removing it here.

2023-06-02 06:42 UTC, groninge01 commented on components/built-badge/lib/built-by-tooltips.ts
> +export const BuiltByTooltips: { [type: string]: string } = {
Made it generic.

2023-06-06 08:32 UTC, groninge01 commented on lib/services/pool/pool-util.ts
> +            return 'Gyro pool';
Updated this.

2023-06-12 05:49 UTC, groninge01 commented on modules/pool/detail/components/warning/PoolWarningThirdParty.tsx
> +import { Box, HStack, Link } from '@chakra-ui/react';
Removed popup, will add the banner image as soon as it's ready.

2023-06-13 08:53 UTC, danielmkm approved these changes

2023-06-13 09:05 UTC, merged